name: flutter_media_notification
version: 1.2.6

author: aliyazdi75 <ma.yazdi75@gmail.com>
description: Flutter Media Notification helps you to show your media notification and control streaming media beyond your flutter app.
homepage: https://github.com/aliyazdi75/flutter_media_notification

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.tarafdari.flutter_media_notification
    pluginClass: FlutterMediaNotificationPlugin